### PR TITLE
Add redirects

### PR DESCRIPTION
**Pull request by SeaJerry**

### CODE REVIEW

**Comment by SeaJerry** [comment]
The home redirect destination required an external link; when I initially tried `/# / 301` as the file path destination, it would fail.

**Comment by SeaJerry** [comment]
@gracexu94 https://www.loom.com/share/ec1531ef736e4fff94b111e519758e03?sid=11cab8d7-b27c-4186-acb1-342ca0786b45

**Comment by SeaJerry** [comment]
The page would fail, no content would appear.

**Comment by gracexu94** [comment]
Went down a bit of a rabbithole with this one and tried a bunch of different configurations, but the answer was actually in [the Cloudflare docs](https://developers.cloudflare.com/pages/platform/redirects/#:~:text=To%20use%20redirects%20on%20Cloudflare,root%20directory%20of%20the%20repository.) the whole time -- using the Cloudflare `_redirects` file won't work because of the /#/ in the URL. Urls with a hash in them get evaluated as fragments which aren't supported in the source url (only the target urls) in the `_redirects` file. 

As a workaround, I added some client-side JS for the redirect functionality, and also used the [eleventy-plugin-metagen](https://www.npmjs.com/package/eleventy-plugin-metagen) plugin to generate meta tags with canonical links which should help minimize impact on SEO. Bonus, since the original site had very few SEO tags, the additional tags generated should lead to better OG/Twitter/etc. cards (compare 
Screen Shot 2023-10-20 at 10 52 37 AM

and

Screen Shot 2023-10-20 at 10 52 50 AM

Follow-up task: add additional logo sizes

**Review by johnphamvan — APPROVED** [review]
Thanks for the effort @gracexu94 @SeaJerry!

**Pull request merged**
